name: "CI"
on:
  push:
    branches:
      - 'develop'
      - 'stage'
      - 'master'
  pull_request:
    branches:
      - 'develop'
      - 'stage'
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  build_and_test_go:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456
          POSTGRES_DB: ultimatedivisiondb_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Set up Go 1.17.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.17.4
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Build
        run: go install ./... .
      - name: Lint
        uses: BoostyLabs/golangci-lint@master
        with:
          args: "run"
        env:
          GOROOT: ""
      - name: Test
        run: go test ./... .

  build_and_lint_web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm i --force
        working-directory: ./web/console
      - name: Lint
        run: npm run lint
        working-directory: ./web/console
      - name: Build
        run: npm run build
        working-directory: ./web/console

  count_lines_of_code:
    if: github.event_name == 'pull_request'
    name: Count lines of code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: pr
      - name: Checkout base code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
          path: base
      - name: Count Lines Of Code
        id: loc
        run: |
          curl -OL https://github.com/vearutop/sccdiff/releases/download/v1.0.1/linux_amd64.tar.gz && tar xf linux_amd64.tar.gz
          OUTPUT=$(cd pr && ../sccdiff -basedir ../base)
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"
          echo "::set-output name=diff::$OUTPUT"
      - name: Comment Code Lines
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          header: LOC
          message: |
            ### Lines Of Code
            ${{ steps.loc.outputs.diff }}

  backend_check_PR_size:
    if: github.event_name == 'pull_request'
    name: Backend check PR size
    runs-on: ubuntu-latest
    steps:
      - uses: ookami-kb/gh-pr-size-watcher@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # required
          errorSize: 450 # optional
          errorMessage: ':no_entry: PR has more than **{allowed} additions**. Split it into smaller PRs.' # optional
          warningSize: 400 # optional
          warningMessage: ':warning: PR has more than **{allowed} additions**. Consider splitting it into smaller PRs.' # optional
          excludeTitle: 'PR_SIZE_SKIP' # to skip validation if PR title matches regex, optional
          excludePaths:  | # to exclude some files from calculation, optional
            README.md
            **/test/resources/*.json
            **/go.mod
            **/go.sum
            **/*_test.go
            **/*.yml
            **/*.json
            **/*.html
            **/*.css
            **/*.scss
            **/*.jsx

  frontend_check_PR_size:
    if: github.event_name == 'pull_request'
    name: Frontend check PR size
    runs-on: ubuntu-latest
    steps:
      - uses: ookami-kb/gh-pr-size-watcher@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }} # required
          errorSize: 900 # optional
          errorMessage: ':no_entry: PR has more than **{allowed} additions**. Split it into smaller PRs.' # optional
          warningSize: 850 # optional
          warningMessage: ':warning: PR has more than **{allowed} additions**. Consider splitting it into smaller PRs.' # optional
          excludeTitle: 'PR_SIZE_SKIP' # to skip validation if PR title matches regex, optional
          excludePaths:  | # to exclude some files from calculation, optional
            README.md
            **/test/resources/*.json
            **/go.mod
            **/go.sum
            **/*_test.go
            **/*.yml
            **/*.go
            **/*.js
            **/*.ts
            **/*.json
